title: WEC-Bench
description: WEC-Bench is a resource for testing Wave Energy Converter motors at laboratory and small scale Powering the Blue Economy (PBE) scales. 
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman